<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net8.0</TargetFrameworks>
    <RootNamespace>DevExtreme.AspNet.Data.Tests</RootNamespace>
    <OutputType>Exe</OutputType>
    <IsTestProject>False</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectCapability Remove="TestContainer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevExtreme.AspNet.Data\DevExtreme.AspNet.Data.csproj" />
    <PackageReference Include="System.Data.SqlClient" />
    <PackageReference Include="xunit.v3.assert" />
    <PackageReference Include="xunit.v3.core" />
  </ItemGroup>

</Project>
