name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  release-packages:
    runs-on: windows-latest

    steps:
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-quality: ga
        dotnet-version: 3.1

    - uses: actions/checkout@v4

    - run: |
        curl -L -o secure-file.zip https://github.com/appveyor/secure-file/releases/download/1.0.1/secure-file.zip
        tar -xf secure-file.zip 
        # dotnet secure-file.dll -decrypt .\net\DevExtreme.AspNet.Data\1.txt.enc -secret ${{ secrets.TEMP_DEV_AV_SECRET }} -salf ${{ secrets.TEMP_DEV_AV_SALT }}
        dotnet pack .\net\DevExtreme.AspNet.Data --configuration=Release --include-symbols
