name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  release-packages:
    runs-on: ubuntu-latest

    env:
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

    steps:
    - uses: actions/checkout@v4

    - run: |
        wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb
        sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb
        curl -L -o /opt/secure-file.zip https://github.com/appveyor/secure-file/releases/download/1.0.1/secure-file.zip
        unzip /opt/secure-file.zip -d /opt/secure-file
        # dotnet /opt/secure-file/secure-file.dll -decrypt net/DevExtreme.AspNet.Data/release.snk.enc -secret ${{ env.RELEASE_KEY_SECRET }}
        dotnet pack net/DevExtreme.AspNet.Data --configuration=Release --include-symbols